name: example-command
on:
  repository_dispatch:
    types: [example-command]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        id: comment
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          # body: |
          #   > Pull request message successfully deployed
          reactions: ${{ github.event.client_payload.slash_command.args.named.reaction || 'hooray' }}
      - name: Edit comment with error message
        if: steps.comment.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.comment.outputs.error-message }}
      - name: Deploy
        uses: steebchen/kubectl@v2.0.0
        id: deploy
        with:
          config: dGVzdC12YWx1ZQo=
          version: v1.22.2
          command: get pods 2>&1 | tee /github/home/deploy.log; exit "${PIPESTATUS[0]}"
      - name: Catch error message
        if: failure()
        id: deploy_error
        run: |
          echo $PWD
          error=$(cat /home/runner/work/_temp/_github_home/deploy.log) >> $GITHUB_OUTPUT
      - name: Comment error message
        if: steps.deploy_error.outputs.error
        uses: peter-evans/create-or-update-comment@v4
        id: comment_error
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > [!CAUTION]
            > Deployment failed with following error:
            > **${{ steps.deploy_error.outputs.error }}**
          reactions: "-1"